"""Plain-language explanations for every evidence flag shown in the UI/PDF."""

from __future__ import annotations

FLAG_EXPLANATIONS: dict[str, str] = {
    "Urgency language detected": (
        "The body uses time-pressure phrasing (immediately, within 24 hours, "
        "account will be locked) that is designed to skip normal verification."
    ),
    "Suspicious shortened link found": (
        "A URL shortener (bit.ly, tinyurl, t.co, etc.) hides the true destination. "
        "Phishing kits routinely wrap credential-harvesting pages this way."
    ),
    "Lookalike domain detected": (
        "The sender domain is a near-miss of a well-known brand (extra letters, "
        "digit substitutions, or brand-name + login/verify bait). This is a "
        "classic homograph / typosquat lure."
    ),
    "Suspicious link to lookalike domain": (
        "A URL in the body points at a lookalike of a trusted brand rather than "
        "that organisation's real website. Recipients are being steered to a "
        "credential-harvesting page."
    ),
    "Link domain does not match claimed sender": (
        "The message claims to be from a known organisation, but an embedded "
        "link goes to a different domain that is not one of that organisation's "
        "official sites."
    ),
    "Credential harvesting language": (
        "The message asks the recipient to confirm a password, OTP, or banking "
        "detail on an external page — a primary phishing objective."
    ),
    "Brand impersonation in display name": (
        "The From display name copies a trusted organisation (PayPal, Microsoft, "
        "bank, internal executive) while the actual mailbox does not belong to them."
    ),
    "Generic greeting with sensitive ask": (
        "A vague greeting ('Dear Customer') combined with a high-stakes request "
        "is typical of mass-mailed phishing rather than a genuine account notice."
    ),
    "Request for payment / gift cards": (
        "The message pushes an unusual payment path (gift cards, crypto, urgent "
        "wire). This pattern is common in BEC / CEO-fraud campaigns."
    ),
    "Suspicious attachment reference": (
        "The body references an invoice, shipment, or voicemail attachment that "
        "would typically carry malware or a credential-stealing document."
    ),
    "IP-based URL in body": (
        "A link points at a raw IP address instead of a hostname. Legitimate brands "
        "almost never host account pages this way."
    ),
    "Link display text does not match URL": (
        "Visible link text names a trusted site while the actual href goes somewhere "
        "else — a common HTML phishing trick."
    ),
    "SPF: FAIL": (
        "The sending server is not authorised in the domain's SPF record. The "
        "message was likely sent from infrastructure the domain owner does not control."
    ),
    "SPF: PASS": (
        "The sending IP is listed in the domain's SPF record. This is expected "
        "for legitimate mail but can still be abused if the domain itself is malicious."
    ),
    "SPF: NONE": (
        "No SPF record was published for the sending domain, so the receiving "
        "server could not verify whether this host was allowed to send as that domain."
    ),
    "DKIM: FAIL": (
        "The DKIM cryptographic signature is missing or does not validate. The "
        "message may have been altered in transit or never signed by the claimed domain."
    ),
    "DKIM: PASS": (
        "The DKIM signature verified. Header and body bytes match what the signing "
        "domain originally sent."
    ),
    "DKIM: NONE": (
        "No DKIM signature was present. Many consumer and attacker-operated "
        "mailboxes skip signing entirely."
    ),
    "DMARC: FAIL": (
        "DMARC alignment failed (SPF and/or DKIM did not align with the From "
        "domain). Receiving servers are entitled to quarantine or reject this mail."
    ),
    "DMARC: PASS": (
        "DMARC policy alignment succeeded. The From domain is consistent with "
        "authenticated SPF or DKIM identity."
    ),
    "DMARC: NONE": (
        "The From domain has not published a DMARC policy, so there is no "
        "domain-owner instruction on how to handle authentication failures."
    ),
    "Return-Path mismatch with From address": (
        "Bounces would go to a different mailbox than the visible From address. "
        "Spoofed mail often uses a throwaway envelope sender."
    ),
    "Missing Authentication-Results header": (
        "The message has no Authentication-Results from the receiving MTA, which "
        "makes SPF/DKIM/DMARC harder to trust and is unusual on well-configured mail."
    ),
    "Message-ID domain does not match From domain": (
        "The Message-ID was generated by a host that does not belong to the From "
        "domain — a weak but useful supporting signal of spoofing."
    ),
    "IP flagged as VPN/hosting provider": (
        "The connecting IP belongs to a cloud, VPS, or VPN range rather than a "
        "residential or corporate ISP. Compromised or rented servers are a favourite "
        "phishing origin."
    ),
    "Sender IP does not match From domain MX": (
        "The origin IP is not among the mail exchangers published for the From "
        "domain, which is unexpected for first-party transactional mail."
    ),
    "Origin country unusual for claimed brand": (
        "The GeoIP country of the sending host does not match where the impersonated "
        "brand actually operates its mail infrastructure."
    ),
    "TOR exit node suspected": (
        "The origin IP matches a known anonymity-network exit. Legitimate mail "
        "platforms do not originate customer notifications from Tor."
    ),
    "ASN belongs to a bulletproof host": (
        "The origin ASN has a reputation for ignoring abuse complaints — frequently "
        "used to host phishing kits and throwaway SMTP relays."
    ),
    "Could not extract a public originating IP": (
        "Received headers did not contain a usable public IP, so geolocation is "
        "incomplete. This can happen with internal relays or stripped headers."
    ),
    "No content anomalies detected": (
        "The NLP classifier did not find urgency, brand-spoof, or credential-harvest "
        "patterns in the subject or body."
    ),
    "No origin-risk indicators": (
        "Origin IP, hosting reputation, and domain-age checks did not raise a "
        "material geolocation or infrastructure risk flag."
    ),
    "Partial analysis: malformed MIME": (
        "The message did not parse cleanly as RFC 822. Findings below are based on "
        "whatever headers and text could be recovered."
    ),
}


def explain_flag(flag: str) -> str:
    if flag in FLAG_EXPLANATIONS:
        return FLAG_EXPLANATIONS[flag]
    if flag.startswith("Domain registered"):
        return (
            "WHOIS intelligence shows a very recently created sending domain. "
            "Phishing infrastructure is often registered, used, and discarded within days."
        )
    if flag.startswith("ML classifier:"):
        return (
            "The TF-IDF + logistic regression model scored this message as likely "
            "phishing based on wording similar to known lures in the training set."
        )
    if flag.startswith("Attachment listed:"):
        return (
            "The MIME structure includes this filename. v1 lists names only and does "
            "not unpack or scan the payload."
        )
    return "This signal contributed to the overall fraud score and should be reviewed by an analyst."
